LOCALBASE = /usr/local
X11BASE = /usr/X11R6
       
CFLAGS = -I$(LOCALBASE)/include -I$(X11BASE)/include
LDFLAGS = -L$(LOCALBASE)/lib -L$(X11BASE)/lib
LDLIBS = -lX11 -lcairo
BIN = see
       
all: $(BIN)
      
output : walla
